### ISSUE TITLE
Acceptance environment setup

### ISSUE THREAD

**Issue by JSTLWK** [KA-Huis/space-management#44]
## Description

Before we can deploy tickets to production, we need to make sure it's according to the acceptance criteria and it's not breaking the application. We therefore need an environment for this. This test environment will allow us to test the tickets one more time on an environment similar to the production environment. It also enables us to showcase our work more easily to our stakeholders.

The test environment is set up by the use ploi.io. This service is easily accessible and has ease of use for the users. 

## Errors that we came across in this task

- Redis use; test environment is set for sessions. 
- .gitignore changes.

## Sub Tasks

- [x]  #45
- [x] #46
- [x] #47

**Comment by cyrildewit** [comment]
## Environment details

* **Link:** https://acc-ka.jstlwk.dev/
