### ISSUE TITLE
Improve acceptance setup for te session driver

### ISSUE THREAD

**Issue by JSTLWK** [KA-Huis/space-management#46]
Documentation
- https://laracasts.com/discuss/channels/laravel/table-homesteadsessions-does-not-exist

**Comment by cyrildewit** [comment]
@Hoopless could you explain what the objective of this ticket is? Thanks.

**Comment by JSTLWK** [comment]
@cyrildewit The test application uses the session database table, this requires a migration to be added to the repo.
```php
Schema::create('sessions', function ($table) {
    $table->string('id')->unique();
    $table->unsignedInteger('user_id')->nullable();
    $table->string('ip_address', 45)->nullable();
    $table->text('user_agent')->nullable();
    $table->text('payload');
    $table->integer('last_activity');
});
```

However, we should decide if we want **Redis** to take over the **sessions** or to have the **sessions** in the **database**.

**Comment by cyrildewit** [comment]
@Hoopless ahh thanks for the explanation. I can remember this issue now. I think we can create the database migration within the repository and put the creation and dropping code within an environment check. I don't think we need a Redis server in the acceptance environment for now. We can discuss the need for this within the next sprint.

Something like:

`$this->app->environment('acceptance')`. Maybe we could create a service for this including constants for the available environments.

What do you think about this? This is something I can pick up before the sprint ends.

**Comment by JSTLWK** [comment]
Good idea!

**Comment by cyrildewit** [comment]
See linked pull request.

**Comment by JSTLWK** [comment]
Merged, makes the ticket completed. The migration has been added and used by the acceptance envoriment.
