### ISSUE TITLE
UUID, ID or HashIds for REST API

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#81]
### Resources

* https://dev.mysql.com/doc/refman/8.0/en/binary-varbinary.html
* https://docs.oracle.com/cd/E17952_01/mysql-8.0-en/string-type-syntax.html#:~:text=The%20BINARY%20attribute%20is%20a,on%20numeric%20character%20code%20values.
* https://instagram-engineering.com/sharding-ids-at-instagram-1cf5a71e5a5c
* https://github.com/vinkla/hashids
* https://www.percona.com/blog/2019/11/22/uuids-are-popular-but-bad-for-performance-lets-discuss/
* 

## Advice

After discussing this ticket with @Hoopless and @MiKessels, we've decided to use the standard ID. UUID and HashID will require some extra research to properly implement it.

**Comment by cyrildewit** [comment]
## Advice

After discussing this ticket with @Hoopless and @MiKessels, we've decided to use the standard ID. UUID and HashID will require some extra research to properly implement it.

**Comment by JSTLWK** [comment]
## Advise

I've found out that using HashIDs are case sensitive. We have an option to disable this, but this will cut the number of uses in half. So we are trying to find a way how to solve this. 

We have found out the following regarding Hash ids;
- Using unique in the database might require `varbinary` or binary.
How to implement this can be found at https://laracasts.com/discuss/channels/eloquent/varbinary-equivalent-in-eloquent

**Comment by JSTLWK** [comment]
Asked for advice from one of my colleagues. He will advise UUID since this is already implemented into Laravel which makes it easier for the application to understand and use.

**Comment by cyrildewit** [comment]
@Hoopless Although it's good to think about what is easier to implement within Laravel, I think it's still interessant to research and learn more about HashID's. 

I don't think we have to store the HashId in the database, but only the ID. That's the whole purpose of this right 😂 . 

So: /users/asfasdf
asfasdf => 203
SELECT * FROM users WHERE id = 203

**Comment by JSTLWK** [comment]
Hey @cyrildewit, Yes agreed. However, I wanted to note how my (work) colleagues thought about it. I am sure we will implement this feature. But indeed, in the database. I will pick the ticket (https://github.com/KA-Huis/space-management/issues/67) up and will change the information in the ticket itself.

**Comment by JSTLWK** [comment]
Hey @cyrildewit, Yes agreed. However, I wanted to note how my (work) colleagues thought about it. I am sure we will implement this feature. But indeed, in the database. I will pick the ticket (https://github.com/KA-Huis/space-management/issues/67) up and will change the information in the ticket itself.

**Comment by cyrildewit** [comment]
@Hoopless I understand where you comment came from. I just reacted with what thought popped up in my mind. I realised something stupid.
