### ISSUE TITLE
Run atisan command `system:acl:synchronise-roles-and-permissions` after each deployment

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#91]
## Description

In ticket #79 an automatic roles and permission synchronisation solution has been created. This synchronisation needs to be run after each deployment.

## Tasks

- [x] Add to the deployment script of the acceptance environment.

**Comment by Hoopless** [comment]
<img width="1904" alt="Screenshot 2022-04-26 at 15 50 27" src="https://user-images.githubusercontent.com/14042234/165315104-83036e2a-c51f-4bba-b1b0-f8274c5eeb1b.png">

Added the command to the deploy script.

**Comment by cyrildewit** [comment]
@Hoopless please prevent sharing sensitive information on this platform 😂 . You can see the IP address and server instance in of ploi.io.
